title: "My Tech Blog"
description: "개발 · 보안 · 클라우드 공부 기록"

# Minimal Mistakes 원격 테마
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

# ✅ GitHub Pages에서 허용되는 플러그인 (필수)
plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      sidebar:
        nav: docs
      toc: true
      toc_sticky: true

  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      sidebar:
        nav: docs
      toc: true
      toc_sticky: true
