title: "My Tech Blog"
description: "개발 · 보안 · 클라우드 공부 기록"

# Minimal Mistakes 원격 테마
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

# ✅ GitHub Pages에서 허용되는 플러그인 (필수)
plugins:
  - jekyll-include-cache

# (옵션) 상단 메뉴
main:
  - title: "About"
    url: /about/
  - title: "Categories"
    url: /categories/
  - title: "Frida"
    url: /frida/

