title: "My Tech Blog"
description: "개발 · 보안 · 클라우드 공부 기록"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache

# ✅ _pages 폴더를 빌드 대상으로 등록
collections:
  pages:
    output: true
    permalink: /:path/   # _pages/android/index.md   -> /android/
                         # _pages/frida/install_guide.md -> /frida/install_guide/

# 기본값(페이지/포스트에 사이드바 자동 적용)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      sidebar:
        nav: docs
      toc: true
      toc_sticky: true

  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      sidebar:
        nav: docs
      toc: true
      toc_sticky: true
